# Meta
name: 모조ㆍ로그
description: 오픈소스, 공유 문화, 웹 기술, 프로그래밍, 생활
url: http://mozo.kr
baseurl: ''

timezone: 'Asia/Seoul'
permalink: pretty

# SEO
logo:
author: 홍영택 (yeongtaek Hong)
twitter:
  username: mozodev
social:
  name: 'mozolog'
  links:
    - http://twitter.com/mozodev

# google
google_analytics: 'UA-74529228-1'

# Build
exclude:
  - node_modules
  - .jekyll-metadata
  - .gitignore
  - .ruby-version
  - Gemfile
  - Gemfile.lock
  - README.md
  - gulpfile.js
  - package.json
gems:
  - jekyll-github-metadata
  - jekyll-paginate
  - jekyll-seo-tag

kramdown:
  input: GFM
  syntax_highlighter: rouge

paginate: 15
repository: mozodev/mozodev.github.io